# Generated by Django 4.2.7 on 2024-03-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='if_custom',
            new_name='if_moc',
        ),
    ]
