# Generated by Django 4.2.7 on 2024-03-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_minifigure_date_added_set_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='minifigure',
            name='owner_name',
            field=models.CharField(default='default_user', max_length=20),
        ),
    ]
