# Generated by Django 4.2.7 on 2024-03-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_minifigure_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minifigure',
            name='cover_image',
        ),
    ]
