# Generated by Django 4.2.7 on 2024-03-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_set_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='minifigure',
            name='image',
            field=models.ImageField(default='default_picture.jpg', upload_to='profile_pictures'),
        ),
    ]
