# Generated by Django 4.2.7 on 2024-03-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_minifigure_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minifigure',
            name='image',
        ),
    ]
