# Generated by Django 4.2.7 on 2024-03-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_minifigure_era'),
    ]

    operations = [
        migrations.AddField(
            model_name='minifigure',
            name='old_picture_path',
            field=models.CharField(default='minifigure_default.png', max_length=50),
        ),
    ]
