# Generated by Django 4.2.7 on 2024-03-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_file_remove_minifigure_gallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
