# Generated by Django 4.2.7 on 2024-03-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='minifigure_default.png', upload_to='gallery')),
            ],
        ),
        migrations.RemoveField(
            model_name='minifigure',
            name='gallery_image',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='gallery',
            name='minifigure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.minifigure'),
        ),
    ]
