# Generated by Django 4.2.7 on 2024-03-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_image_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='minifigure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.minifigure'),
        ),
    ]
